### ISSUE TITLE
Installation of dependencies on OSX

### ISSUE THREAD

**Issue by agrimm** [davidworkman9/drawingtotext#4]
How do I install the dependencies for this on OSX?

I tried running make, and it complained about dwg.h, which I assume is related to libreDWG. I couldn't find anything for libreDWG on OSX.

	$ make
	g++ -ggdb -o drawingtotext OutputFormatText.cpp OutputFormatConsole.cpp OutputFormatTypes.cpp InputFormatDXF.cpp GetInsertions.cpp InputFormatDWG.cpp AutoCADConverter.cpp -ldxflib -I/usr/include/gdal -lredwg
	In file included from InputFormatDWG.cpp:1:
	./InputFormatDWG.h:11:11: fatal error: 'dwg.h' file not found
	        #include <dwg.h>
	                 ^
	1 error generated.
	In file included from AutoCADConverter.cpp:2:
	./InputFormatDWG.h:11:11: fatal error: 'dwg.h' file not found
	        #include <dwg.h>
	                 ^
	1 error generated.
	make: *** [drawingtotext] Error 1
	$

Please note this is very low importance - I don't need to use drawingtotext myself, I'm just trying to run the tests for the npm package textract (dbashford/textract).

**Comment by davidworkman9** [comment]
Sorry for the late response. I am not sure. This isn't something I'm maintaining anymore. Our company ended up going with a commercial solution.

**Comment by agrimm** [comment]
That's fine.
